# Generated by Django 2.1.4 on 2019-10-06 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_characterclasses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('version', models.CharField(blank=True, max_length=256, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Cantrip'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')])),
                ('school', models.CharField(choices=[('Abjuration', 'Abjuration'), ('Conjuration', 'Conjuration'), ('Divination', 'Divination'), ('Enchantment', 'Enchantment'), ('Evocation', 'Evocation'), ('Illusion', 'Illusion'), ('Necromancy', 'Necromancy'), ('Transmutation', 'Transmutation')], max_length=256)),
                ('casting_time_amount', models.PositiveSmallIntegerField()),
                ('casting_time_unit', models.CharField(choices=[('ACTION', 'Action'), ('BONUS_ACTION', 'Bonus Action'), ('HOUR', 'Hour'), ('MINUTE', 'Minute'), ('NO_ACTION', 'No Action'), ('REACTION', 'Reaction'), ('SPECIAL', 'Special')], max_length=50)),
                ('casting_time_description', models.CharField(blank=True, max_length=256, null=True)),
                ('component_verbal', models.BooleanField(default=False)),
                ('component_somatic', models.BooleanField(default=False)),
                ('component_material', models.BooleanField(default=False)),
                ('component_material_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('range_type', models.CharField(choices=[('SELF', 'Self'), ('TOUCH', 'Touch'), ('RANGED', 'Ranged'), ('SIGHT', 'Sight'), ('UNLIMITED', 'Unlimited')], max_length=50)),
                ('range_distance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Range distance (ft)')),
                ('duration_type', models.CharField(choices=[('CONCENTRATION', 'Concentration'), ('INSTANTANEOUS', 'Instantaneous'), ('SPECIAL', 'Special'), ('TIME', 'Time'), ('UNTIL_DISPELLED', 'Until Dispelled'), ('UNTIL_DISPELLED_OR_TRIGGERED', 'Until Dispelled or Triggered')], max_length=50)),
                ('duration_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('ROUND', 'Round'), ('MINUTE', 'Minute'), ('HOUR', 'Hour'), ('DAY', 'Day')], max_length=50, null=True)),
                ('description', models.TextField(max_length=8192)),
                ('ritual', models.BooleanField(default=False)),
                ('higher_level', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spells', to=settings.AUTH_USER_MODEL)),
                ('classes', models.ManyToManyField(related_name='spells', to='app_characterclasses.CharacterClass')),
            ],
            options={
                'ordering': ['level', 'name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpellAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('aoe_type', models.CharField(blank=True, choices=[('CONE', 'Cone'), ('CUBE', 'Cube'), ('CYLINDER', 'Cylinder'), ('LINE', 'Line'), ('SPHERE', 'Sphere'), ('SQUARE', 'Square')], max_length=50, null=True)),
                ('aoe_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('part_of_weapon_attack', models.BooleanField(default=False)),
                ('save_type', models.CharField(blank=True, choices=[('STR', 'STR'), ('CON', 'CON'), ('DEX', 'DEX'), ('INT', 'INT'), ('WIS', 'WIS'), ('CHA', 'CHA')], max_length=50, null=True)),
                ('spell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spell_additional_info', to='app_spells.Spell')),
            ],
          options={
            'managed': True,
          }
        ),
        migrations.CreateModel(
            name='SpellCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=2048)),
                ('value', models.CharField(max_length=8192)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='app_spells.Spell')),
            ],
          options={
            'managed': True,
          }
        ),
        migrations.CreateModel(
            name='SpellTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=256, unique=True)),
            ],
          options={
            'managed': True,
          }
        ),
        migrations.AddField(
            model_name='spelladditionalinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='spell_additional_info', to='app_spells.SpellTag')
        ),
        migrations.AlterUniqueTogether(
            name='spell',
            unique_together={('name', 'version')},
        ),
    ]
