# Generated by Django 2.1.4 on 2018-12-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_characterclasses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_time', models.CharField(choices=[('1_ACTION', '1 Action'), ('1_BONUS', '1 Bonus Action'), ('1_REACTION', '1 Reaction'), ('1_MINUTE', '1 Minute'), ('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('8_HOURS', '8 Hours'), ('12_HOURS', '12 Hours'), ('24_HOURS', '24 Hours')], max_length=10)),
                ('component_material', models.CharField(blank=True, max_length=100, null=True)),
                ('component_material_cost', models.PositiveIntegerField(default=0)),
                ('component_verbal', models.BooleanField()),
                ('component_somatic', models.BooleanField()),
                ('concentration', models.BooleanField()),
                ('description', models.TextField(max_length=2000)),
                ('duration', models.CharField(choices=[('INSTANTANEOUS', 'Instantaneous'), ('1_ROUND', '1 Round'), ('1_MINUTE', '1 Minute'), ('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('2_HOURS', '2 Hour'), ('8_HOURS', '8 Hours'), ('24_HOURS', '24 Hours'), ('7_DAYS', '7 Days'), ('10_DAYS', '10 Days'), ('30_DAYS', '30 Days'), ('UNTIL_DISPELLED', 'Until Dispelled'), ('OTHER', 'Other')], max_length=15)),
                ('duration_other', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Cantrip'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('range', models.PositiveSmallIntegerField(null=True, verbose_name='range (ft)')),
                ('ritual', models.BooleanField()),
                ('school', models.CharField(choices=[('ABJ', 'Abjuration'), ('CON', 'Conjuration'), ('DIV', 'Divination'), ('ENC', 'Enchantment'), ('EVO', 'Evocation'), ('ILL', 'Illusion'), ('NEC', 'Necromancy'), ('TRA', 'Transmutation')], max_length=4)),
                ('source_book', models.CharField(blank=True, choices=[('PHB', "Player's Handbook"), ('EE', "Elemental Evil Player's Companion"), ('SCAG', "Sword Coast Adventurer's Guide"), ('XGE', "Xanathar's Guide to Everything")], max_length=4, null=True)),
                ('source_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to=settings.AUTH_USER_MODEL)),
                ('spell_list', models.ManyToManyField(related_name='spells', to='app_characterclasses.CharacterClass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
    ]
