# Generated by Django 2.1.4 on 2018-12-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_time', models.CharField(choices=[('1_ACTION', '1 Action'), ('1_BONUS', '1 Bonus Action'), ('1_REACTION', '1 Reaction'), ('1_MINUTE', '1 Minute'), ('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('8_HOURS', '8 Hours'), ('12_HOURS', '12 Hours'), ('24_HOURS', '24 Hours')], max_length=10)),
                ('component_material', models.CharField(blank=True, max_length=100, null=True)),
                ('component_material_cost', models.IntegerField(default=0)),
                ('component_verbal', models.BooleanField()),
                ('component_somatic', models.BooleanField()),
                ('concentration', models.BooleanField()),
                ('level', models.IntegerField(choices=[(0, 'Cantrip'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')])),
                ('name', models.CharField(max_length=50)),
                ('ritual', models.BooleanField()),
                ('school', models.CharField(max_length=50)),
                ('source_book', models.CharField(blank=True, choices=[('phb', "Player's Handbook"), ('ee', "Elemental Evil Player's Companion"), ('scag', "Sword Coast Adventurer's Guide"), ('xge', "Xanathar's Guide to Everything")], max_length=4, null=True)),
                ('source_page_number', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1500)),
                ('spell_list', models.ManyToManyField(to='app_classes.CharacterClass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
    ]
