# Generated by Django 2.1.4 on 2018-12-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(choices=[('INSTANTANEOUS', 'Instantaneous'), ('1_ROUND', '1 Round'), ('1_MINUTE', '1 Minute'), ('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('2_HOURS', '2 Hour'), ('8_HOURS', '8 Hours'), ('24_HOURS', '24 Hours'), ('7_DAYS', '7 Days'), ('10_DAYS', '10 Days'), ('30_DAYS', '30 Days'), ('UNTIL_DISPELLED', 'Until Dispelled'), ('OTHER', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cantrip'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(choices=[('ABJ', 'Abjuration'), ('CON', 'Conjuration'), ('DIV', 'Divination'), ('ENC', 'Enchantment'), ('EVO', 'Evocation'), ('ILL', 'Illusion'), ('NEC', 'Necromancy'), ('TRA', 'Transmutation')], max_length=4),
        ),
        migrations.AlterField(
            model_name='spell',
            name='source_book',
            field=models.CharField(blank=True, choices=[('PHB', "Player's Handbook"), ('EE', "Elemental Evil Player's Companion"), ('SCAG', "Sword Coast Adventurer's Guide"), ('XGE', "Xanathar's Guide to Everything")], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='source_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
