# Generated by Django 2.1.4 on 2018-12-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0002_auto_20181223_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='range (ft)'),
        ),
    ]
