# Generated by Django 2.1.4 on 2018-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0002_auto_20181224_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='spell_list',
            field=models.ManyToManyField(to='app_characterclasses.CharacterClass'),
        ),
    ]
