# Generated by Django 2.1.4 on 2019-10-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0002_auto_20191007_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spellca',
            old_name='spell',
            new_name='owner',
        ),
    ]
