# Generated by Django 2.1.4 on 2018-12-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0003_auto_20181224_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='spell_list',
            field=models.ManyToManyField(related_name='spell_list', to='app_characterclasses.CharacterClass'),
        ),
    ]
