# Generated by Django 2.1.4 on 2018-12-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0003_spell_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='component_material_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
