# Generated by Django 2.1.4 on 2018-12-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0004_auto_20181223_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='component_material_cost',
            field=models.IntegerField(default=0),
        ),
    ]
