# Generated by Django 2.1.4 on 2018-12-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0005_auto_20181224_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='spell_list',
        ),
    ]
