# Generated by Django 2.1.4 on 2018-12-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0005_auto_20181223_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='component_material_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
