# Generated by Django 2.1.4 on 2018-12-27 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_characterclasses', '0002_auto_20181227_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_spells', '0006_auto_20181227_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spells', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_list',
            field=models.ManyToManyField(to='app_characterclasses.CharacterClass'),
        ),
    ]
