# Generated by Django 2.1.4 on 2018-12-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0008_auto_20181227_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to=settings.AUTH_USER_MODEL),
        ),
    ]
