# Generated by Django 2.1.4 on 2018-12-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0009_auto_20181227_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='spell_list',
            field=models.ManyToManyField(related_name='spells', to='app_characterclasses.CharacterClass'),
        ),
    ]
