# Generated by Django 2.1.4 on 2018-12-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0010_auto_20181227_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='component_material_cost',
        ),
        migrations.AddField(
            model_name='spell',
            name='casting_time_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='source_book_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(choices=[('1_ACTION', '1 Action'), ('1_BONUS', '1 Bonus Action'), ('1_REACTION', '1 Reaction'), ('1_MINUTE', '1 Minute'), ('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('8_HOURS', '8 Hours'), ('12_HOURS', '12 Hours'), ('24_HOURS', '24 Hours'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='spell',
            name='component_material',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(default='None', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spell',
            name='source_book',
            field=models.CharField(blank=True, choices=[('PHB', "Player's Handbook"), ('EE', "Elemental Evil Player's Companion"), ('SCAG', "Sword Coast Adventurer's Guide"), ('XGE', "Xanathar's Guide to Everything"), ('OTHER', 'Other')], max_length=4, null=True),
        ),
    ]
