# Generated by Django 2.1.4 on 2018-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spells', '0011_auto_20181228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='source_book',
            field=models.CharField(blank=True, choices=[('PHB', "Player's Handbook"), ('EE', "Elemental Evil Player's Companion"), ('SCAG', "Sword Coast Adventurer's Guide"), ('XGE', "Xanathar's Guide to Everything"), ('OTHER', 'Other')], max_length=5, null=True),
        ),
    ]
