# Generated by Django 2.1.4 on 2019-10-27 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileca',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='app_profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='userca',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to=settings.AUTH_USER_MODEL),
        ),
    ]
