# Generated by Django 2.1.4 on 2018-12-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_characterclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
