# Generated by Django 2.1.5 on 2019-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=4000)),
                ('source_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
