# Generated by Django 2.1.5 on 2019-01-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conditions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conditions',
            new_name='Condition',
        ),
    ]
