# Generated by Django 2.1.4 on 2019-01-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conditions', '0002_auto_20190124_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['name']},
        ),
    ]
