# Generated by Django 2.1.4 on 2019-10-07 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_conditions', '0003_auto_20190131_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=2048)),
                ('value', models.CharField(max_length=8192)),
            ],
        ),
        migrations.RemoveField(
            model_name='condition',
            name='source_page_number',
        ),
        migrations.AddField(
            model_name='condition',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.TextField(max_length=8192),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=156, unique=True),
        ),
        migrations.AddField(
            model_name='conditionca',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='app_conditions.Condition'),
        ),
    ]
