# Generated by Django 2.1.4 on 2019-10-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conditions', '0004_auto_20191007_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionca',
            old_name='condition',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
