# Generated by Django 2.1.5 on 2019-10-30 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('size', models.CharField(max_length=256)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype', models.CharField(blank=True, max_length=256, null=True)),
                ('alignment', models.CharField(choices=[('Lawful Good', 'Lawful Good'), ('Neutral Good', 'Neutral Good'), ('Chaotic Good', 'Chaotic Good'), ('Lawful Neutral', 'Lawful Neutral'), ('True Neutral', 'True Neutral'), ('Chaotic Neutral', 'Chaotic Neutral'), ('Lawful Evil', 'Lawful Evil'), ('Neutral Evil', 'Neutral Evil'), ('Chaotic Evil', 'Chaotic Evil')], max_length=256)),
                ('armor_class', models.PositiveSmallIntegerField()),
                ('hit_point', models.PositiveSmallIntegerField()),
                ('hit_dice', models.CharField(choices=[('1d3', '1d3'), ('1d4', '1d4'), ('1d6', '1d6'), ('1d8', '1d8'), ('1d10', '1d10'), ('1d12', '1d12')], max_length=256)),
                ('ability_str', models.PositiveSmallIntegerField()),
                ('ability_dex', models.PositiveSmallIntegerField()),
                ('ability_con', models.PositiveSmallIntegerField()),
                ('ability_int', models.PositiveSmallIntegerField()),
                ('ability_wis', models.PositiveSmallIntegerField()),
                ('challenge_rating', models.CharField(choices=[('0', '0'), ('1/8', '1/8'), ('1/4', '1/4'), ('1/2', '1/2'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=256)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monsters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['challenge_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonsterAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=4000, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('attack_bonus', models.SmallIntegerField(default=0)),
                ('damage_dice', models.CharField(blank=True, max_length=256, null=True)),
                ('damage_bonus', models.SmallIntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=1000)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterConditionImmunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_immunity', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_immunities', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterDamageImmunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_immunity', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_immunities', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterDamageResistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_resistance', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_resistances', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterDamageVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_vulnerability', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_vulnerabilities', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterLegendaryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_bonus', models.SmallIntegerField(default=0)),
                ('content', models.TextField(blank=True, max_length=4000, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legendary_actions', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=4000, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, choices=[('Athletics', 'Athletics'), ('Acrobatics', 'Acrobatics'), ('Sleight of Hand', 'Sleight of Hand'), ('Stealth', 'Stealth'), ('Arcana', 'Arcana'), ('History', 'History'), ('Investigation', 'Investigation'), ('Nature', 'Nature'), ('Religion', 'Religion'), ('Animal Handling', 'Animal Handling'), ('Insight', 'Insight'), ('Medicine', 'Medicine'), ('Perception', 'Perception'), ('Survival', 'Survival'), ('Deception', 'Deception'), ('Intimidation', 'Intimidation'), ('Performance', 'Performance'), ('Persuasion', 'Persuasion')], max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSpecialAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=4000, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('attack_bonus', models.SmallIntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_abilities', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeds', to='app_monsters.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=4000, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='app_monsters.Monster')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='monster',
            unique_together={('name', 'version')},
        ),
    ]
