# Generated by Django 2.1.5 on 2019-10-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='armor_class_notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
