# Generated by Django 2.1.5 on 2019-10-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monsters', '0002_monster_armor_class_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.CharField(choices=[('Fine', 'Fine'), ('Diminutive', 'Diminutive'), ('Small', 'Tiny'), ('Medium', 'Medium'), ('Large', 'Large'), ('Huge', 'Huge'), ('Gargantuan', 'Gargantuan'), ('Colossal', 'Colossal')], max_length=256),
        ),
    ]
