# Generated by Django 2.1.5 on 2019-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monsters', '0004_auto_20191031_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.CharField(choices=[('Fine', 'Fine'), ('Diminutive', 'Diminutive'), ('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Huge', 'Huge'), ('Gargantuan', 'Gargantuan'), ('Colossal', 'Colossal')], max_length=256),
        ),
    ]
