# Generated by Django 2.1.5 on 2019-11-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_monsters', '0006_auto_20191102_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monsterspeed',
            old_name='speed',
            new_name='value',
        ),
    ]
