# Generated by Django 2.1.5 on 2019-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monsters', '0007_auto_20191102_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsteraction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterconditionimmunity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterdamageimmunity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterdamageresistance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterdamagevulnerability',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterlanguage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterlegendaryaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterreaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monstersave',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monstersense',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterskill',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterspecialabilities',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monsterspeed',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='monstertrait',
            name='owner',
        ),
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='condition_immunities',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_immunities',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_resistances',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_vulnerabilities',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='languages',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='legendary_actions',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='saves',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='senses',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='special_abilities',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='speeds',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='traits',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='MonsterAction',
        ),
        migrations.DeleteModel(
            name='MonsterConditionImmunity',
        ),
        migrations.DeleteModel(
            name='MonsterDamageImmunity',
        ),
        migrations.DeleteModel(
            name='MonsterDamageResistance',
        ),
        migrations.DeleteModel(
            name='MonsterDamageVulnerability',
        ),
        migrations.DeleteModel(
            name='MonsterLanguage',
        ),
        migrations.DeleteModel(
            name='MonsterLegendaryAction',
        ),
        migrations.DeleteModel(
            name='MonsterReaction',
        ),
        migrations.DeleteModel(
            name='MonsterSave',
        ),
        migrations.DeleteModel(
            name='MonsterSense',
        ),
        migrations.DeleteModel(
            name='MonsterSkill',
        ),
        migrations.DeleteModel(
            name='MonsterSpecialAbilities',
        ),
        migrations.DeleteModel(
            name='MonsterSpeed',
        ),
        migrations.DeleteModel(
            name='MonsterTrait',
        ),
    ]
