# Generated by Django 2.1.5 on 2019-11-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monsters', '0008_auto_20191104_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='actions',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='legendary_actions',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='special_abilities',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='traits',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='monsterca',
            name='name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='monsterca',
            name='value',
            field=models.CharField(max_length=8192),
        ),
    ]
